### ISSUE TITLE
NullPointerException on cluster

### ISSUE THREAD

**Issue by Igorock** [qubole/kinesis-sql#16]
Application is successfully working in local mode but it fails on cluster in client mode with an error:

`java.lang.NullPointerException
        at org.apache.spark.sql.kinesis.KinesisSource.prevBatchShardInfo(KinesisSource.scala:216)`

Full stack-trace:

`2018-08-10 12:52:37 ERROR MicroBatchExecution:91 - Query [id = a1c2934d-a65e-4b4c-b111-e0ecb2d62133, runId = bb95b4e8-6ce4-4bd9-b4b5-61c0a44939ae] terminated with error
java.lang.NullPointerException
        at org.apache.spark.sql.kinesis.KinesisSource.prevBatchShardInfo(KinesisSource.scala:216)
        at org.apache.spark.sql.kinesis.KinesisSource.getOffset(KinesisSource.scala:105)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:267)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:264)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:264)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:128)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:121)
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:117)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:189)
Exception in thread "main" org.apache.spark.sql.streaming.StreamingQueryException: null
=== Streaming Query ===
Identifier: [id = a1c2934d-a65e-4b4c-b111-e0ecb2d62133, runId = bb95b4e8-6ce4-4bd9-b4b5-61c0a44939ae]
Current Committed Offsets: {KinesisSource[testing-kinesis-spark]: {"metadata":{"streamName":"testing-kinesis-spark","batchId":"0"},"shardId-000000000000":{"iteratorType":"AT_TIMESTAMP","iteratorPosition":"1533905549906"}}}
Current Available Offsets: {KinesisSource[testing-kinesis-spark]: {"metadata":{"streamName":"testing-kinesis-spark","batchId":"0"},"shardId-000000000000":{"iteratorType":"AT_TIMESTAMP","iteratorPosition":"1533905549906"}}}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
SerializeFromObject [encodeusingserializer(input[0, java.lang.Object, true], false) AS value#44]
+- MapPartitions <function1>, obj#43: com.test.app.AppTask$AppOutput
   +- DeserializeToObject decodeusingserializer(cast(value#41 as binary), com.tr.common.messagebroker.MessageType$ComputationMessage, false), obj#42: com.tr.common.messagebroker.MessageType$ComputationMessage
      +- SerializeFromObject [encodeusingserializer(input[0, java.lang.Object, true], false) AS value#41]
         +- MapPartitions <function1>, obj#40: com.tr.common.messagebroker.MessageType$ComputationMessage
            +- DeserializeToObject decodeusingserializer(cast(value#37 as binary), com.tr.common.messagebroker.MessageType$ComputationMessage, false), obj#39: com.tr.common.messagebroker.MessageType$ComputationMessage
               +- SerializeFromObject [encodeusingserializer(input[0, java.lang.Object, true], false) AS value#37]
                  +- MapElements <function1>, class scala.Tuple4, [StructField(_1,StringType,true), StructField(_2,StringType,true), StructField(_3,StringType,true), StructField(_4,DecimalType(38,0),true)], obj#36: com.tr.common.messagebroker.MessageType$ComputationMessage
                     +- DeserializeToObject newInstance(class scala.Tuple4), obj#35: scala.Tuple4
                        +- Aggregate [streamName#15, partitionKey#16, data#17], [streamName#15, partitionKey#16, data#17, count(1) AS count#25L]
                           +- Project [cast(streamName#6 as string) AS streamName#15, cast(partitionKey#7 as string) AS partitionKey#16, cast(data#5 as string) AS data#17]
                              +- StreamingExecutionRelation KinesisSource[testing-kinesis-spark], [data#5, streamName#6, partitionKey#7, sequenceNumber#8, approximateArrivalTimestamp#9]

        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:295)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:189)
Caused by: java.lang.NullPointerException
        at org.apache.spark.sql.kinesis.KinesisSource.prevBatchShardInfo(KinesisSource.scala:216)
        at org.apache.spark.sql.kinesis.KinesisSource.getOffset(KinesisSource.scala:105)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:267)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:264)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:264)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:128)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:121)
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:117)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)
        ... 1 more
`

**Comment by itsvikramagr** [comment]
@Igorock - Exception depends upon your application code and your cluster. Can you look at the executor logs to see if the execution of the first batch was successful? 

It would be great if you can come up with the exact issue which can be addressed.

**Comment by Igorock** [comment]
logs from executor: 
18/08/13 08:43:48 DEBUG PoolingHttpClientConnectionManager: Connection [id: 0][route: {s}->https://kinesis.us-west-1.amazonaws.com:443] can be kept alive for 60.0 seconds
18/08/13 08:43:48 DEBUG DefaultManagedHttpClientConnection: http-outgoing-0: set socket timeout to 0
18/08/13 08:43:48 DEBUG PoolingHttpClientConnectionManager: Connection released: [id: 0][route: {s}->https://kinesis.us-west-1.amazonaws.com:443][total kept alive: 1; route allocated: 1 of 50; total allocated: 1 of 50]
18/08/13 08:43:48 DEBUG request: Received successful response: 200, AWS Request ID: 60571d29-c24c-4fbc-9b9d-8bc26d3b6bee
18/08/13 08:43:48 DEBUG requestId: x-amzn-RequestId: 60571d29-c24c-4fbc-9b9d-8bc26d3b6bee
18/08/13 08:43:48 DEBUG KinesisSourceRDD: Milli secs behind is 0
18/08/13 08:43:48 DEBUG TaskMemoryManager: Task 0 release 256.0 KB from org.apache.spark.unsafe.map.BytesToBytesMap@41801e61
18/08/13 08:43:48 DEBUG TaskMemoryManager: Task 0 release 64.0 MB from org.apache.spark.sql.catalyst.expressions.VariableLengthRowBasedKeyValueBatch@54cbd9e
18/08/13 08:43:48 INFO KinesisSourceRDD: Task Completed
18/08/13 08:43:48 INFO KinesisSourceRDD: Batch 0 : Committing End Shard position for shardId-000000000000
18/08/13 08:43:48 DEBUG UserGroupInformation: PrivilegedAction as:ec2-user (auth:SIMPLE) from:org.apache.hadoop.fs.FileContext.getAbstractFileSystem(FileContext.java:331)
18/08/13 08:43:48 DEBUG PoolingHttpClientConnectionManager: Connection manager is shutting down
18/08/13 08:43:48 DEBUG IdleConnectionReaper: Reaper thread: 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.IdleConnectionReaper.run(IdleConnectionReaper.java:181)

**Comment by itsvikramagr** [comment]
@Igorock - you may want to check if you are able to write to this location 
[$checkpointLocation]/sources/0/shard-commit/0  

Closing this since it looks to be a cluster setup issue.  Can you send an email to me if you have any other questions? My email id is vagrawal @ qubole.com

**Comment by vishal98** [comment]
i am facing similar issue on cluster..how did it got fixed?
