### ISSUE TITLE
NullPointerException when output dir already exists for CSV sink

### ISSUE THREAD

**Issue by ealtamir** [qubole/kinesis-sql#20]
Hi folks. Thanks for writing this awesome library. It's been really useful. I wanted to report a small problem I'm seeing. Here's a small fragment of my code:

```  
def main(args: Array[String]): Unit = {

  import sparkSession.implicits._

  val kinesis = sparkService.getKinesisStructuredStream(
    config.getString("kinesis.streamName"),
    config.getString("kinesis.endpointURL"),
    config.getString("kinesis.startingPosition")
  )

  val processedEvent = kinesis.as[Event]
    .map(SNSEventProcessor.process)
    .filter(col("eventId").isNotNull)

  processedEvent.writeStream
    .outputMode("append")
    .format("csv")
    .option("checkpointLocation", config.getString("spark.app.checkpointDir"))
    .option("path", "./output/csv_output")
    .start()
    .awaitTermination()
}
```

When the `./output` doesn't exist, the stream runs without problems. However, when I terminate it and then start it again I get the following exception:

```
Caused by: java.lang.NullPointerException
	at org.apache.spark.sql.kinesis.KinesisSource.prevBatchShardInfo(KinesisSource.scala:216)
	at org.apache.spark.sql.kinesis.KinesisSource.getOffset(KinesisSource.scala:105)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5$$anonfun$apply$5.apply(MicroBatchExecution.scala:268)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:267)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$5.apply(MicroBatchExecution.scala:264)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$constructNextBatch(MicroBatchExecution.scala:264)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:128)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:121)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:271)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:121)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:117)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:279)
	... 1 more
```

It may be possible that there's something I'm doing wrong. If that's the case I'd be very grateful if you point it out. If you need more info to find out what might be the cause of this let me know. Thanks!

**Comment by itsvikramagr** [comment]
What is your checkpoint location? 

can you check if files are created here:   config.getString("spark.app.checkpointDir")/source/<batch-id>/shard-commits

**Comment by itsvikramagr** [comment]
@ealtamir - let me know if you are able to figure out the problem?

**Comment by ealtamir** [comment]
@itsvikramagr unfortunately I haven't been able to recreate the bug. Sorry for crying wolf. I'll close this issue for now. Thanks for your time.
