### ISSUE TITLE
Need to add option --jars spark-sql-kinesis_2.11-2.3.0.jar when running spark-submit

### ISSUE THREAD

**Issue by joeyfaherty** [qubole/kinesis-sql#34]
Hi,

I am using version 2.3.0 of this library with Spark 2.3.0, which I package together into a fat jar to be run on a remote env via spark-submit.

But, when I run the fat jar with spark submit I get the error:

> Exception in thread “main” java.lang.ClassNotFoundException: Failed to find data source: kinesis. Please find packages at http://spark.apache.org/third-party-projects.html
    at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:635)
    at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:159) 

> Caused by: java.lang.ClassNotFoundException: kinesis.DefaultSource
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23$$anonfun$apply$15.apply(DataSource.scala:618)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23$$anonfun$apply$15.apply(DataSource.scala:618)
    at scala.util.Try$.apply(Try.scala:192)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23.apply(DataSource.scala:618)
    at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23.apply(DataSource.scala:618)
    at scala.util.Try.orElse(Try.scala:84)
    at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:618)
    ... 28 more

To fix this I need to add `--jars spark-sql-kinesis_2.11-2.3.0.jar` option when running spark-submit, which solves the issue.. but I am wondering why I see this even when I can see the classes are packaged within the fat jar?

Thanks in advance

**Comment by itsvikramagr** [comment]
@joeyfaherty - I am not sure I can help you here. You might have to debug the way the fat jar is created.
