### ISSUE TITLE
Null pointer exception when trying to read stream in cluster mode

### ISSUE THREAD

**Issue by HariprasadAllaka1612** [qubole/kinesis-sql#74]
Hi, 
I am trying to read a kinesis stream from spark code. 

When i submit the job in deploy-mode as client everything works fine. but when i am trying to submit the job in cluster mode, i get null pointer exception 

java.lang.NullPointerException
	at org.apache.spark.sql.kinesis.KinesisSourceProvider.createContinuousReader(KinesisSourceProvider.scala:175)
	at org.apache.spark.sql.kinesis.KinesisSourceProvider.createContinuousReader(KinesisSourceProvider.scala:38)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:204)
	at com.playngodataengg.dao.DataAccessS3.readStream(DataAccessS3.scala:135)
	at com.playngodataengg.controller.TransactionStreamTransform.processData(TransactionStreamTransform.scala:57)
	at com.playngodataengg.action.TransactionStreamData$.main(TransactionStreamData.scala:14)
	at com.playngodataengg.action.TransactionStreamData.main(TransactionStreamData.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)

Could you please help me resolve this

**Comment by itsvikramagr** [comment]
I have absolutely no idea about this. I looked into the code and there is nothing which is specific to the mode.

Were you able to find the issue?

**Comment by itsvikramagr** [comment]
@HariprasadAllaka1612 - I am closing this issue. Please re-open it if you are able to narrow done the issue to this module.
