### ISSUE TITLE
Spark job is failing because of AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 503

### ISSUE THREAD

**Issue by levontr** [qubole/kinesis-sql#75]
Hi,
My spark job is failing from time to time due to this issue error:

`ERROR Executor: Exception in task 8.2 in stage 7091.0 (TID 569538)
java.lang.IllegalStateException: Error while Fetching Shard Iterator
	at org.apache.spark.sql.kinesis.KinesisReader.org$apache$spark$sql$kinesis$KinesisReader$$retryOrTimeout(KinesisReader.scala:238)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3.apply(KinesisReader.scala:120)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3.apply(KinesisReader.scala:120)
	at org.apache.spark.sql.kinesis.KinesisReader.runUninterruptibly(KinesisReader.scala:202)
	at org.apache.spark.sql.kinesis.KinesisReader.getShardIterator(KinesisReader.scala:118)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getShardIterator(KinesisSourceRDD.scala:128)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getNext(KinesisSourceRDD.scala:144)
	at org.apache.spark.sql.kinesis.KinesisSourceRDD$$anon$1.getNext(KinesisSourceRDD.scala:120)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$JoinIterator.hasNext(Iterator.scala:212)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 503; Error Code: null; Request ID: f85526c5-c619-6271-aeb9-79cd252d8265)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2276)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2252)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.executeGetShardIterator(AmazonKinesisClient.java:1162)
	at org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.AmazonKinesisClient.getShardIterator(AmazonKinesisClient.java:1138)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3$$anonfun$apply$1.apply(KinesisReader.scala:121)
	at org.apache.spark.sql.kinesis.KinesisReader$$anonfun$3$$anonfun$apply$1.apply(KinesisReader.scala:121)
	at org.apache.spark.sql.kinesis.KinesisReader.org$apache$spark$sql$kinesis$KinesisReader$$retryOrTimeout(KinesisReader.scala:226)
	... 29 more`

Any suggestion how can I overcome it?

**Comment by itsvikramagr** [comment]
@levontr - I could not make a lot out of the stack trace. It seems to be failing with this error 

> org.apache.spark.sql.kinesis.shaded.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 503; Error Code: null; Request ID: f85526c5-c619-6271-aeb9-79cd252d8265) 

Can you check if you have provided the correct input to your application? or else can you help me with more info about the issue.

**Comment by levontr** [comment]
@itsvikramagr sorry for writing back with delay. I missed your comment.
This is a continuously running spark job which most of the time works without any issue. And just sometimes it fails with this exception.
What kind if input would potentially trigger this exception?
What kind of details would you need to better understand the issue?

**Comment by itsvikramagr** [comment]
@levontr 
looks like we have some temporary error from AWS and then the application failed because of issues in  TimeourOrRetry logic (issue #50). Let me work on a PR for it.

**Comment by arnehuang** [comment]
I face this as well. https://github.com/qubole/kinesis-sql/pull/76

**Comment by itsvikramagr** [comment]
fixed via #79 and #76
